column_mapping = {
    'id': 'station_id',
    'latitude': 'latitude',
    'longitude': 'longitude',
    'Code postal': 'zip_code',
    'pop': 'pop',
    'Adresse': 'address',
    'Ville': 'city',
    'services': 'services',
    'prix': 'price',
    'rupture': 'shortage',
    'horaires': 'schedules',
    'Prix Gazole mis à jour le': 'diesel_price_updated_at',
    'Prix Gazole': 'diesel_price',
    'Prix SP95 mis à jour le': 'sp95_price_updated_at',
    'Prix SP95': 'sp95_price',
    'Prix E85 mis à jour le': 'e85_price_updated_at',
    'Prix E85': 'e85_price',
    'Prix GPLc mis à jour le': 'gplc_price_updated_at',
    'Prix GPLc': 'gplc_price',
    'Prix E10 mis à jour le': 'e10_price_updated_at',
    'Prix E10': 'e10_price',
    'Prix SP98 mis à jour le': 'sp98_price_updated_at',
    'Prix SP98': 'sp98_price',
    'Début rupture e10 (si temporaire)': 'e10_start_shortage',
    'Type rupture e10': 'e10_shortage_type',
    'Début rupture sp98 (si temporaire)': 'sp98_start_shortage',
    'Type rupture sp98': 'sp98_shortage_type',
    'Début rupture sp95 (si temporaire)': 'sp95_start_shortage',
    'Type rupture sp95': 'sp95_shortage_type',
    'Début rupture e85 (si temporaire)': 'e85_start_shortage',
    'Type rupture e85': 'e85_shortage_type',
    'Début rupture GPLc (si temporaire)': 'gplc_start_shortage',
    'Type rupture GPLc': 'gplc_shortage_type',
    'Début rupture gazole (si temporaire)': 'diesel_start_shortage',
    'Type rupture gazole': 'diesel_shortage_type',
    'Carburants disponibles': 'available_fuel',
    'Carburants indisponibles': 'unavailable_fuel',
    'Carburants en rupture temporaire': 'temporary_out_of_stock_fuel',
    'Carburants en rupture definitive': 'definitive_out_of_stock_fuel',
    'Automate 24-24 (oui/non)': 'automate_2424',
    'Services proposés': 'provided_services',
    'Département': 'department',
    'code_departement': 'department_code',
    'Région': 'region',
    'code_region': 'region_code',
    'horaires détaillés': 'detailed_schedules',
}